Hacky fix for GCC15+ compilation
`src/active.c:759:9: error: too many arguments to function 'set_limits_from_pp_table'; expected 0, have 1`
A gcc update probably "broke" it (stopped ignoring the error), or changed the behaviour of `()`